@echo off
REM Flutter Project Backup Script
REM Created: 2025-12-06
REM Project: SmartLedger - Multi-Account Household Ledger

echo =========================================
echo   Flutter Project Backup Started
echo =========================================
echo.

REM Set backup directory (default: %USERPROFILE%\SmartLedger_backups)
set BACKUP_DIR=%USERPROFILE%\SmartLedger_backups

REM Resolve project directory to this script's folder
set PROJECT_DIR=%~dp0
REM Remove trailing backslash if present
if "%PROJECT_DIR:~-1%"=="\" set PROJECT_DIR=%PROJECT_DIR:~0,-1%

REM Create timestamp
for /f "tokens=2-4 delims=/ " %%a in ('date /t') do (set mydate=%%c-%%a-%%b)
for /f "tokens=1-2 delims=/:" %%a in ('time /t') do (set mytime=%%a%%b)
set TIMESTAMP=%mydate%_%mytime%
set BACKUP_NAME=SmartLedger_backup_%TIMESTAMP%
set BACKUP_PATH=%BACKUP_DIR%\%BACKUP_NAME%

echo Creating backup directory...
if not exist "%BACKUP_DIR%" mkdir "%BACKUP_DIR%"
mkdir "%BACKUP_PATH%"

echo.
echo Copying project files...

REM Exclusions (applies to all subfolders)
set EXCLUDE_DIRS=build .dart_tool .idea .vscode node_modules .git .gradle Pods DerivedData ephemeral .symlinks
set EXCLUDE_FILES=*.iml .flutter-plugins .flutter-plugins-dependencies .packages

REM Robocopy options: /E include subdirs, /R:1 /W:1 quick retry, quiet output
set ROBO_OPTS=/E /COPY:DAT /DCOPY:DAT /R:1 /W:1 /NFL /NDL /NJH /NJS /NP

REM Copy source directories
echo   - Copying lib...
robocopy "%PROJECT_DIR%\lib" "%BACKUP_PATH%\lib" %ROBO_OPTS% /XD %EXCLUDE_DIRS% /XF %EXCLUDE_FILES% > nul

echo   - Copying test...
if exist "%PROJECT_DIR%\test" robocopy "%PROJECT_DIR%\test" "%BACKUP_PATH%\test" %ROBO_OPTS% /XD %EXCLUDE_DIRS% /XF %EXCLUDE_FILES% > nul

echo   - Copying android...
if exist "%PROJECT_DIR%\android" robocopy "%PROJECT_DIR%\android" "%BACKUP_PATH%\android" %ROBO_OPTS% /XD %EXCLUDE_DIRS% /XF %EXCLUDE_FILES% > nul

echo   - Copying ios...
if exist "%PROJECT_DIR%\ios" robocopy "%PROJECT_DIR%\ios" "%BACKUP_PATH%\ios" %ROBO_OPTS% /XD %EXCLUDE_DIRS% /XF %EXCLUDE_FILES% > nul

echo   - Copying windows...
if exist "%PROJECT_DIR%\windows" robocopy "%PROJECT_DIR%\windows" "%BACKUP_PATH%\windows" %ROBO_OPTS% /XD %EXCLUDE_DIRS% /XF %EXCLUDE_FILES% > nul

echo   - Copying web...
if exist "%PROJECT_DIR%\web" robocopy "%PROJECT_DIR%\web" "%BACKUP_PATH%\web" %ROBO_OPTS% /XD %EXCLUDE_DIRS% /XF %EXCLUDE_FILES% > nul

echo   - Copying linux...
if exist "%PROJECT_DIR%\linux" robocopy "%PROJECT_DIR%\linux" "%BACKUP_PATH%\linux" %ROBO_OPTS% /XD %EXCLUDE_DIRS% /XF %EXCLUDE_FILES% > nul

echo   - Copying macos...
if exist "%PROJECT_DIR%\macos" robocopy "%PROJECT_DIR%\macos" "%BACKUP_PATH%\macos" %ROBO_OPTS% /XD %EXCLUDE_DIRS% /XF %EXCLUDE_FILES% > nul

echo   - Copying tools...
if exist "%PROJECT_DIR%\tools" robocopy "%PROJECT_DIR%\tools" "%BACKUP_PATH%\tools" %ROBO_OPTS% /XD %EXCLUDE_DIRS% /XF %EXCLUDE_FILES% > nul

echo.
echo Copying configuration files...

REM Copy configuration files
copy "%PROJECT_DIR%\pubspec.yaml" "%BACKUP_PATH%\" > nul 2>&1
copy "%PROJECT_DIR%\pubspec.lock" "%BACKUP_PATH%\" > nul 2>&1
copy "%PROJECT_DIR%\analysis_options.yaml" "%BACKUP_PATH%\" > nul 2>&1
copy "%PROJECT_DIR%\README.md" "%BACKUP_PATH%\" > nul 2>&1
copy "%PROJECT_DIR%\.gitignore" "%BACKUP_PATH%\" > nul 2>&1
copy "%PROJECT_DIR%\.metadata" "%BACKUP_PATH%\" > nul 2>&1

echo.
echo Copying documentation files...

REM Copy all markdown files
for %%f in ("%PROJECT_DIR%\*.md") do (
    echo   - Copying %%~nxf...
    copy "%%f" "%BACKUP_PATH%\" > nul 2>&1
)

REM Copy PowerShell scripts
for %%f in ("%PROJECT_DIR%\*.ps1") do (
    echo   - Copying %%~nxf...
    copy "%%f" "%BACKUP_PATH%\" > nul 2>&1
)

echo.
echo Creating backup info file...

REM Create backup info file
(
echo Backup Information
echo ==================
echo.
echo Backup Date: %date% %time%
echo Backup Name: %BACKUP_NAME%
echo Project Path: %PROJECT_DIR%
echo Backup Path: %BACKUP_PATH%
echo.
echo Included Directories:
echo - lib
echo - test
echo - android
echo - ios
echo - windows
echo - web
echo - linux
echo - macos
echo.
echo Excluded Directories:
echo - build
echo - .dart_tool
echo - .idea
echo - .vscode
echo - node_modules
echo - .git
echo.
echo Restore Instructions:
echo 1. Copy backup folder to desired location
echo 2. Open terminal in backup folder
echo 3. Run: flutter pub get
echo 4. Run: flutter pub run build_runner build --delete-conflicting-outputs
echo 5. Run: flutter run -d windows
echo.
echo Notes:
echo - User data should be backed up using app's backup/restore feature
echo - build/ folder is not backed up, rebuild required after restore
echo - .dart_tool/ folder will be auto-generated by pub get
) > "%BACKUP_PATH%\BACKUP_INFO.txt"

echo.
echo =========================================
echo   Backup Complete!
echo =========================================
echo.
echo Backup Path: %BACKUP_PATH%
echo.
echo See BACKUP_INFO.txt for backup details
echo.

REM List recent backups
echo Recent Backups:
dir /B /O-D "%BACKUP_DIR%" | findstr /R "SmartLedger_backup"

echo.
echo Backup completed successfully!
echo.
echo To compress the backup, use:
echo   Compress-Archive -Path "%BACKUP_PATH%" -DestinationPath "%BACKUP_PATH%.zip"
echo.

pause