part of 'recipe_service.dart';

/// 기본 레시피 Part 2a: 한식 반찬·국·전 (r18–r26)
final List<Recipe> _defaultRecipesPart2a = [
  Recipe(
    id: 'r18',
    localizedNames: {
      'ko': '김치볶음밥',
      'en': 'Kimchi Fried Rice',
      'ar': 'الأرز المقلي بالكيمتشي',
      'de': 'Kimchi-Gebratener Reis',
      'el': 'Ρύζι Τηγανισμένο ΕΤ Κιμτσι',
      'es': 'Arroz frito con kimchi',
      'fr': 'Riz frit au kimchi',
      'hi': 'किमची फ्राइड राइस',
      'it': 'Riso fritto al kimchi',
      'ja': 'キムチチャーハン',
      'nl': 'Kimchi-Gebakken Rijst',
      'pl': 'Smażony ryż z kimchi',
      'pt': 'Arroz Frito com Kimchi',
      'sv': 'Kimchi-Stekt Ris',
      'th': 'ข้าวหอมกิมจิ',
      'tr': 'Kimchi Pilavalı Pilav',
      'vi': 'Cơm Kimchi Chiên',
      'ru': 'Жареный рис с кимчи',
    },
    ingredients: [
      RecipeIngredient(name: '김치', quantity: 0.2, unit: '포기'),
      RecipeIngredient(name: '햄', quantity: 100, unit: 'g'),
      RecipeIngredient(name: '대파', quantity: 0.5, unit: '대'),
      RecipeIngredient(name: '계란', quantity: 1, unit: '개'),
    ],
  ),
  Recipe(
    id: 'r19',
    localizedNames: {
      'ko': '콩나물국',
      'en': 'Bean Sprout Soup',
      'ar': 'حساء براعم الفول السوداني',
      'de': 'Sojabohnenkeim-Suppe',
      'el': 'Σούπα Φλογαρίτες Ξιφίας',
      'es': 'Sopa de brotes de soja',
      'fr': 'Soupe de pousses de soja',
      'hi': 'बीन स्प्राउट सूप',
      'it': 'Zuppa di germogli di soia',
      'ja': '豆もやしスープ',
      'nl': 'Sojaspruitsesop',
      'pl': 'Zupa z kiełków fasoli',
      'pt': 'Sopa de Broto de Feijão',
      'sv': 'Sojabj örkningsoppa',
      'th': 'น้ำซุปงอบไทด์',
      'tr': 'Soya Filizi Çorbası',
      'vi': 'Súp Giá Đậu Xanh',
      'ru': 'Суп из бобовых ростков',
    },
    ingredients: [
      RecipeIngredient(name: '콩나물', quantity: 300, unit: 'g'),
      RecipeIngredient(name: '대파', quantity: 0.5, unit: '대'),
      RecipeIngredient(name: '다진마늘', quantity: 0.5, unit: '큰술'),
    ],
  ),
  Recipe(
    id: 'r20',
    localizedNames: {
      'ko': '소고기무국',
      'en': 'Beef Radish Soup',
      'ar': 'حساء لحم البقر مع الفجل',
      'de': 'Rind-Rettich-Suppe',
      'el': 'Σούπα Βοείας Και Ραπανελλα',
      'es': 'Sopa de ternera y rábano',
      'fr': 'Soupe de bœuf et radis',
      'hi': 'बीफ मूली सूप',
      'it': 'Zuppa di manzo e ravanello',
      'ja': '牛肉大根スープ',
      'nl': 'Rundvlees Rauwkoolsoep',
      'pl': 'Zupa wołowa z rediską',
      'pt': 'Sopa de Carne e Rabanete',
      'sv': 'Nöt-Radis-Soppa',
      'th': 'น้ำซุปเนื้อหมูหัวไชเท้า',
      'tr': 'İne ğ-Radis Çorbası',
      'vi': 'Súp Cá Bò và Cu Đông',
      'ru': 'Суп из говядины и редьки',
    },
    ingredients: [
      RecipeIngredient(name: '소고기', quantity: 200, unit: 'g'),
      RecipeIngredient(name: '무', quantity: 0.3, unit: '개'),
      RecipeIngredient(name: '대파', quantity: 1, unit: '대'),
      RecipeIngredient(name: '다진마늘', quantity: 1, unit: '큰술'),
    ],
  ),
  Recipe(
    id: 'r21',
    localizedNames: {
      'ko': '시금치나물',
      'en': 'Seasoned Spinach',
      'ar': 'سبانخ مطابة',
      'de': 'Gew ürzter Spinat',
      'el': 'Επιχρυασμένα Σπανάκια',
      'es': 'Espinacas sazonadas',
      'fr': 'Épinards assaisonnés',
      'hi': 'पालक',
      'it': 'Spinaci conditi',
      'ja': 'ほうれん草のおひたし',
      'nl': 'Gekruide Spinazie',
      'pl': 'Przyprawiony szpinak',
      'pt': 'Espinafre Temperado',
      'sv': 'Kryddad Spenat',
      'th': 'ผักเห็ดเสม้อ',
      'tr': 'İş ıllı Ispanak',
      'vi': 'Rau Mầm Thơm',
      'ru': 'Приправленный шпинат',
    },
    ingredients: [
      RecipeIngredient(name: '시금치', quantity: 1, unit: '단'),
      RecipeIngredient(name: '다진마늘', quantity: 0.5, unit: '큰술'),
      RecipeIngredient(name: '참기름', quantity: 1, unit: '큰술'),
    ],
  ),
  Recipe(
    id: 'r22',
    localizedNames: {
      'ko': '콩나물무침',
      'en': 'Seasoned Bean Sprouts',
      'ar': 'براعم فول مطابة',
      'de': 'Gew ürzter Sojabohnenkeim',
      'el': 'Επιχρυασμένα Φασόλια Sprouts',
      'es': 'Brotes de soja sazonados',
      'fr': 'Pousses de soja assaisonnées',
      'hi': 'बीन स्प्राउट्स',
      'it': 'Germogli di soia conditi',
      'ja': '豆もやしの和え物',
      'nl': 'Gekruide Sojaspruiten',
      'pl': 'Przyprawione kiełki fasoli',
      'pt': 'Broto de Feijão Temperado',
      'sv': 'Kryddad Sojabönspruntar',
      'th': 'งอบเอฟเกลเญวา',
      'tr': 'İş ıllı Soya Fasulyesi Filizi',
      'vi': 'Giá Đậu Xanh Nêm',
      'ru': 'Приправленные бобовые ростки',
    },
    ingredients: [
      RecipeIngredient(name: '콩나물', quantity: 1, unit: '봉'),
      RecipeIngredient(name: '대파', quantity: 0.2, unit: '대'),
      RecipeIngredient(name: '다진마늘', quantity: 0.5, unit: '큰술'),
    ],
  ),
  Recipe(
    id: 'r23',
    localizedNames: {
      'ko': '멸치볶음',
      'en': 'Stir-fried Anchovies',
      'ar': 'الانشوجة المقلية بسرعة',
      'de': 'Gebratene Sardellen',
      'el': 'Αντσούες Τηγανακες',
      'es': 'Anchoas salteadas',
      'fr': 'Anchois sautés',
      'hi': 'तली हुई एंकोवीज़',
      'it': 'Acciughe saltate',
      'ja': 'イワシ炒め',
      'nl': 'Gebakken Ansjovis',
      'pl': 'Smażone anchois',
      'pt': 'Anchovas Refogadas',
      'sv': 'Stekt Sardiner',
      'th': 'ปลาเล็กน้อยทอด',
      'tr': 'Hızlı Kızartılmış Hamsi',
      'vi': 'Cá Cơm Chiên',
      'ru': 'Жареные анчоусы',
    },
    ingredients: [
      RecipeIngredient(name: '멸치', quantity: 100, unit: 'g'),
      RecipeIngredient(name: '꽈리고추', quantity: 50, unit: 'g'),
      RecipeIngredient(name: '마늘', quantity: 5, unit: '쪽'),
    ],
  ),
  Recipe(
    id: 'r24',
    localizedNames: {
      'ko': '고등어조림',
      'en': 'Braised Mackerel',
      'ar': 'الإسقمري المطهو ببطء',
      'de': 'Gedaempfte Makrele',
      'el': 'Σαρδέλα Μαγειρemes',
      'es': 'Caballa estofada',
      'fr': 'Maquereau braisé',
      'hi': 'ब्रेज्ड मैकेरल',
      'it': 'Sgombro brasato',
      'ja': '鯖の煮付け',
      'nl': 'Geschoofde Makreel',
      'pl': 'Duszona makrela',
      'pt': 'Cavala Braiseada',
      'sv': 'Braserad Makrill',
      'th': 'ปลาอินเดียเศษทอด',
      'tr': 'Karada Uskumru',
      'vi': 'Cá Nục Kho',
      'ru': 'Тушёная скумбрия',
    },
    ingredients: [
      RecipeIngredient(name: '고등어', quantity: 1, unit: '마리'),
      RecipeIngredient(name: '무', quantity: 0.3, unit: '개'),
      RecipeIngredient(name: '양파', quantity: 0.5, unit: '개'),
      RecipeIngredient(name: '대파', quantity: 1, unit: '대'),
    ],
  ),
  Recipe(
    id: 'r25',
    localizedNames: {
      'ko': '오징어볶음',
      'en': 'Stir-fried Squid',
      'ar': 'الحبار المقلي بسرعة',
      'de': 'Gebratene Tintenfisch',
      'el': 'Καλάμαριa Τηγανακά',
      'es': 'Calamares salteados',
      'fr': 'Calmars sautés',
      'hi': 'तली सुआ स्कुलस',
      'it': 'Calamari saltati',
      'ja': 'イカ炒め',
      'nl': 'Gebakken Inktvis',
      'pl': 'Smażone kałamarnice',
      'pt': 'Lula Refogada',
      'sv': 'Stekt Bläckfisk',
      'th': 'ปลาหนูบ',
      'tr': 'Kızartılmış Mürekkep Balığı',
      'vi': 'Mực Xào',
      'ru': 'Жареные кальмары',
    },
    ingredients: [
      RecipeIngredient(name: '오징어', quantity: 2, unit: '마리'),
      RecipeIngredient(name: '양파', quantity: 1, unit: '개'),
      RecipeIngredient(name: '당근', quantity: 0.3, unit: '개'),
      RecipeIngredient(name: '대파', quantity: 1, unit: '대'),
      RecipeIngredient(name: '양배추', quantity: 0.1, unit: '통'),
    ],
  ),
  Recipe(
    id: 'r26',
    localizedNames: {
      'ko': '삼계탕',
      'en': 'Samgyetang',
      'ar': 'سامجياتجان',
      'de': 'Samgyetang',
      'el': 'Σαμγιέτανγ',
      'es': 'Samgyetang',
      'fr': 'Samgyetang',
      'hi': 'सामग्येतांग',
      'it': 'Samgyetang',
      'ja': '参鶏湯',
      'nl': 'Samgyetang',
      'pl': 'Samgyetang',
      'pt': 'Samgyetang',
      'sv': 'Samgyetang',
      'th': 'ซัมเกียตัง',
      'tr': 'Samgyetang',
      'vi': 'Núi Tàu Tiệu',
      'ru': 'Самгетан',
    },
    ingredients: [
      RecipeIngredient(name: '닭고기', quantity: 1, unit: '마리'),
      RecipeIngredient(name: '인삼', quantity: 1, unit: '뿌리'),
      RecipeIngredient(name: '대추', quantity: 5, unit: '개'),
      RecipeIngredient(name: '마늘', quantity: 10, unit: '쪽'),
      RecipeIngredient(name: '찹쌀', quantity: 0.5, unit: '컵'),
    ],
  ),
];
