part of 'recipe_service.dart';

/// 기본 레시피 Part 1a: 한식 찌개·볶음·구이 (r1–r9)
final List<Recipe> _defaultRecipesPart1a = [
  Recipe(
    cuisine: 'Korean',
    id: 'r1',
    localizedNames: {
      'ko': '김치찌개',
      'en': 'Kimchi Stew',
      'ar': 'يخنة الكيمتشي',
      'de': 'Kimchi-Eintopf',
      'el': 'Κιμτσι Στῦ',
      'es': 'Estofado de Kimchi',
      'fr': 'Ragoût de Kimchi',
      'hi': 'किमची स्टू',
      'it': 'Stufato di Kimchi',
      'ja': 'キムチチゲ',
      'nl': 'Kimchi-Stoofpot',
      'pl': 'Gulasz Kimchi',
      'pt': 'Ensopado de Kimchi',
      'sv': 'Kimchi-Gryta',
      'th': 'แกงกิมจิ',
      'tr': 'Kimchi Güveç',
      'vi': 'Cơm Kimchi',
      'ru': 'Тушёное кимчи',
    },
    ingredients: [
      RecipeIngredient(name: 'Kimchi', quantity: 0.25, unit: 'head'),
      RecipeIngredient(name: 'Pork', quantity: 200, unit: 'g'),
      RecipeIngredient(name: 'Tofu', quantity: 0.5, unit: 'block'),
      RecipeIngredient(name: 'Green Onion', quantity: 1, unit: 'stalk'),
      RecipeIngredient(name: 'Onion', quantity: 0.5, unit: 'ea'),
    ],
  ),
  Recipe(
    id: 'r2',
    localizedNames: {
      'ko': '된장찌개',
      'en': 'Soybean Paste Stew',
      'ar': 'يخنة معجون فول الصويا',
      'de': 'Sojapasteneintopf',
      'el': 'Σούπα Σόγιας Ζύμης',
      'es': 'Estofado de pasta de soja',
      'fr': 'Ragoût de pâte de soja',
      'hi': 'सोयाबीन पेस्ट स्टू',
      'it': 'Zuppa di pasta di soia',
      'ja': '味噌チゲ',
      'nl': 'Sojapasta-Stoofpot',
      'pl': 'Gulasz z pasty sojowej',
      'pt': 'Estofado de Pasta de Soja',
      'sv': 'Sojabönor-Gryta',
      'th': 'แกงน้ำจิ้มถั่วเหลือง',
      'tr': 'Soya Macunu Güveç',
      'vi': 'Cơm Tương Đậu Nành',
      'ru': 'Суп из соевой пасты',
    },
    ingredients: [
      RecipeIngredient(name: 'Soybean Paste', quantity: 2, unit: 'tbsp'),
      RecipeIngredient(name: 'Tofu', quantity: 0.5, unit: 'block'),
      RecipeIngredient(name: 'Zucchini', quantity: 0.3, unit: 'ea'),
      RecipeIngredient(name: 'Onion', quantity: 0.5, unit: 'ea'),
      RecipeIngredient(name: 'Potato', quantity: 1, unit: 'ea'),
      RecipeIngredient(name: 'Green Onion', quantity: 0.5, unit: 'stalk'),
    ],
  ),
  Recipe(
    id: 'r3',
    localizedNames: {
      'ko': '제육볶음',
      'en': 'Stir-fried Pork',
      'ar': 'لحم الخنزير المقلي السريع',
      'de': 'Gebratenes Schweinefleisch',
      'el': 'Χοιρινό Ανακατεμένο',
      'es': 'Cerdo salteado',
      'fr': 'Porc sauté',
      'hi': 'भुना हुआ पोर्क',
      'it': 'Maiale saltato',
      'ja': '豚肉炒め',
      'nl': 'Gebakken Varkensviees',
      'pl': 'Smażona wieprzowina',
      'pt': 'Porco Refogado',
      'sv': 'Stekt Fläsk',
      'th': 'หมูผัด',
      'tr': 'Kızarmış Domuz Eti',
      'vi': 'Thịt Lợn Xào',
      'ru': 'Жареная свинина',
    },
    ingredients: [
      RecipeIngredient(name: 'Pork', quantity: 400, unit: 'g'),
      RecipeIngredient(name: 'Onion', quantity: 1, unit: 'ea'),
      RecipeIngredient(name: 'Green Onion', quantity: 1, unit: 'stalk'),
      RecipeIngredient(name: 'Carrot', quantity: 0.3, unit: 'ea'),
    ],
  ),
  Recipe(
    id: 'r4',
    localizedNames: {
      'ko': '계란말이',
      'en': 'Rolled Omelette',
      'ar': 'البيض المقلي الملفوف',
      'de': 'Gerolltes Omelett',
      'el': 'Περιστρεφόμενη Ομελέτα',
      'es': 'Tortilla enrollada',
      'fr': 'Omelette roulée',
      'hi': 'रोल्ड आमलेट',
      'it': 'Omelette arrotolata',
      'ja': '卵焼き',
      'nl': 'Gerold Omelet',
      'pl': 'Zwinięty omlet',
      'pt': 'Omelete Enrolada',
      'sv': 'Rullad Omelett',
      'th': 'ไข่มุกฉ้อย',
      'tr': 'Sarılmış Omlet',
      'vi': 'Trứng Cuộn',
      'ru': 'Рулет из омлета',
    },
    ingredients: [
      RecipeIngredient(name: '계란', quantity: 4, unit: '개'),
      RecipeIngredient(name: '대파', quantity: 0.2, unit: '대'),
      RecipeIngredient(name: '당근', quantity: 0.1, unit: '개'),
    ],
  ),
  Recipe(
    id: 'r5',
    localizedNames: {
      'ko': '미역국',
      'en': 'Seaweed Soup',
      'ar': 'شوربة الأعشاب البحرية',
      'de': 'Algensuppe',
      'el': 'Σούπα Φυκών',
      'es': 'Sopa de algas',
      'fr': 'Soupe aux algues',
      'hi': 'समुद्री शैवाल सूप',
      'it': 'Zuppa di alghe',
      'ja': 'わかめスープ',
      'nl': 'Zeewiersop',
      'pl': 'Zupa z wodorostów',
      'pt': 'Sopa de Alga Marinha',
      'sv': 'Tångsoppa',
      'th': 'น้ำซุปหนองหญ้า',
      'tr': 'Yosun Çorbası',
      'vi': 'Súp Tảo Biển',
      'ru': 'Суп из водорослей',
    },
    ingredients: [
      RecipeIngredient(name: '미역', quantity: 20, unit: 'g'),
      RecipeIngredient(name: '소고기', quantity: 150, unit: 'g'),
      RecipeIngredient(name: '다진마늘', quantity: 1, unit: '큰술'),
    ],
  ),
  Recipe(
    id: 'r6',
    localizedNames: {
      'ko': '닭볶음탕',
      'en': 'Braised Spicy Chicken',
      'ar': 'دجاج حار مهروس',
      'de': 'Geschmortes scharfes Huhn',
      'el': 'Κοτόπουλο Κατσαρόλα Καυτό',
      'es': 'Pollo estofado picante',
      'fr': 'Poulet braisé épicé',
      'hi': 'मसालेदार चिकन',
      'it': 'Pollo brasato piccante',
      'ja': '鶏肉の辛煮',
      'nl': 'Geschoofde Pikante Kip',
      'pl': 'Duszony pikantny kurczak',
      'pt': 'Frango Braiseado Apimentado',
      'sv': 'Bräst Kryddig Kyckling',
      'th': 'ไก่จำปาหวานแกง',
      'tr': 'Tavuk Güveç Baharat',
      'vi': 'Gà Nướng Cay',
      'ru': 'Тушёная острая курица',
    },
    ingredients: [
      RecipeIngredient(name: '닭고기', quantity: 1, unit: '마리'),
      RecipeIngredient(name: '감자', quantity: 2, unit: '개'),
      RecipeIngredient(name: '당근', quantity: 0.5, unit: '개'),
      RecipeIngredient(name: '양파', quantity: 1, unit: '개'),
      RecipeIngredient(name: '대파', quantity: 1, unit: '대'),
    ],
  ),
  Recipe(
    id: 'r7',
    localizedNames: {
      'ko': '삼겹살 구이',
      'en': 'Grilled Pork Belly',
      'ar': 'لحم الخنزير المشوي',
      'de': 'Gegrillter Schweinebauch',
      'el': 'Χοιρινή Κοιλιά Ψημένη',
      'es': 'Panceta de cerdo a la parrilla',
      'fr': 'Poitrine de porc grillée',
      'hi': 'ग्रिल्ड पोर्क बेली',
      'it': 'Pancetta di maiale alla griglia',
      'ja': 'サムギョプサル',
      'nl': 'Gegrilde Varkensbuik',
      'pl': 'Grillowany boczek wieprzowy',
      'pt': 'Pancetta de Porco Grelhada',
      'sv': 'Grillad Svinfläsk',
      'th': 'หลังหมูย่าง',
      'tr': 'Izgara Domuz Karnı',
      'vi': 'Thịt Lợn Nướng',
      'ru': 'Жареная свиная грудинка',
    },
    ingredients: [
      RecipeIngredient(name: '돼지고기', quantity: 600, unit: 'g'),
      RecipeIngredient(name: '마늘', quantity: 10, unit: '쪽'),
      RecipeIngredient(name: '양파', quantity: 1, unit: '개'),
      RecipeIngredient(name: '버섯', quantity: 100, unit: 'g'),
      RecipeIngredient(name: '상추', quantity: 20, unit: '장'),
    ],
  ),
  Recipe(
    id: 'r8',
    localizedNames: {
      'ko': '수육',
      'en': 'Boiled Pork Slices',
      'ar': 'شرائح لحم الخنزير المسلوقة',
      'de': 'Gekochte Schweinefleischscheiben',
      'el': 'Χοιρινό Φέτες Βραστά',
      'es': 'Lonchas de cerdo hervido',
      'fr': 'Tranches de porc bouilli',
      'hi': 'उबला हुआ पोर्क',
      'it': 'Fette di maiale bollito',
      'ja': '茹で豚肉',
      'nl': 'Gekookte Varkensschijven',
      'pl': 'Gotowane plastry wieprzowiny',
      'pt': 'Fatias de Porco Cozidas',
      'sv': 'Kokta Fläskskivor',
      'th': 'หมูนุ่มเค็ม',
      'tr': 'Haşlanmış Domuz Eti Dilimleri',
      'vi': 'Lát Thịt Lợn Luộc',
      'ru': 'Варёная свинина',
    },
    ingredients: [
      RecipeIngredient(name: '돼지고기', quantity: 600, unit: 'g'),
      RecipeIngredient(name: '양파', quantity: 1, unit: '개'),
      RecipeIngredient(name: '대파', quantity: 2, unit: '대'),
      RecipeIngredient(name: '마늘', quantity: 10, unit: '쪽'),
    ],
  ),
  Recipe(
    id: 'r9',
    localizedNames: {
      'ko': '닭갈비',
      'en': 'Spicy Grilled Chicken',
      'ar': 'دجاج مشوي حار',
      'de': 'Scharfes gegrilltes Huhn',
      'el': 'Κοτόπουλο Ψημένο Καυτό',
      'es': 'Pollo a la parrilla picante',
      'fr': 'Poulet grillé épicé',
      'hi': 'मसालेदार ग्रिल्ड चिकन',
      'it': 'Pollo alla griglia piccante',
      'ja': '辛い鶏肉焼き',
      'nl': 'Pittig Gegrilde Kip',
      'pl': 'Pikantny grillowany kurczak',
      'pt': 'Frango Grelhado Apimentado',
      'sv': 'Kryddig Grillad Kyckling',
      'th': 'ไก่ย่างเผ็ด',
      'tr': 'Baharatlı Izgara Tavuk',
      'vi': 'Gà Nướng Cay',
      'ru': 'Острая жареная курица',
    },
    ingredients: [
      RecipeIngredient(name: '닭고기', quantity: 500, unit: 'g'),
      RecipeIngredient(name: '양배추', quantity: 0.25, unit: '통'),
      RecipeIngredient(name: '고구마', quantity: 1, unit: '개'),
      RecipeIngredient(name: '대파', quantity: 1, unit: '대'),
    ],
  ),
];
