part of 'recipe_service.dart';

/// 기본 레시피 Part 2b: 한식 반찬·국·전 (r27–r34)
final List<Recipe> _defaultRecipesPart2b = [
  Recipe(
    id: 'r27',
    localizedNames: {
      'ko': '칼국수',
      'en': 'Kalguksu',
      'ar': 'كالجوكسو',
      'de': 'Kalguksu',
      'el': 'Κάλγουχ',
      'es': 'Kalguksu',
      'fr': 'Kalguksu',
      'hi': 'कालगुक्सु',
      'it': 'Kalguksu',
      'ja': 'カルグクス',
      'nl': 'Kalguksu',
      'pl': 'Kalguksu',
      'pt': 'Kalguksu',
      'sv': 'Kalguksu',
      'th': 'คัลกุกสู',
      'tr': 'Kalguksu',
      'vi': 'Kalguksu',
      'ru': 'Кальгуксу',
    },
    ingredients: [
      RecipeIngredient(name: '칼국수면', quantity: 2, unit: '인분'),
      RecipeIngredient(name: '바지락', quantity: 200, unit: 'g'),
      RecipeIngredient(name: '애호박', quantity: 0.3, unit: '개'),
      RecipeIngredient(name: '감자', quantity: 1, unit: '개'),
      RecipeIngredient(name: '대파', quantity: 0.5, unit: '대'),
    ],
  ),
  Recipe(
    id: 'r28',
    localizedNames: {
      'ko': '만두국',
      'en': 'Dumpling Soup',
      'ar': 'حساء الفطائر',
      'de': 'Knödel-Suppe',
      'el': 'Σούπα Ζυμαρικών',
      'es': 'Sopa de dumplings',
      'fr': 'Soupe de raviolis',
      'hi': 'डम्पलिंग सूप',
      'it': 'Zuppa di ravioli',
      'ja': '餅スープ',
      'nl': 'Dumplingsoep',
      'pl': 'Zupa z pierogi',
      'pt': 'Sopa de Pastel',
      'sv': 'Klimpsoppa',
      'th': 'น้ำแกงมันโด้',
      'tr': 'Mandu Çorbası',
      'vi': 'Cơm Bánh Chiên',
      'ru': 'Суп с пельменями',
    },
    ingredients: [
      RecipeIngredient(name: '만두', quantity: 10, unit: '개'),
      RecipeIngredient(name: '계란', quantity: 1, unit: '개'),
      RecipeIngredient(name: '대파', quantity: 0.5, unit: '대'),
      RecipeIngredient(name: '김', quantity: 1, unit: '장'),
    ],
  ),
  Recipe(
    id: 'r29',
    localizedNames: {
      'ko': '육개장',
      'en': 'Spicy Beef Soup',
      'ar': 'حساء اللحم البقري الحار',
      'de': 'Scharfe Rindersuppe',
      'el': 'Τσιγαρομένη Σούπα Βόειας',
      'es': 'Sopa de ternera picante',
      'fr': 'Soupe de bœuf épicée',
      'hi': 'मसालेदार बीफ सूप',
      'it': 'Zuppa di manzo piccante',
      'ja': 'ユッケジャン',
      'nl': 'Pikante Rundvleessoep',
      'pl': 'Pikantna zupa wołowa',
      'pt': 'Sopa Picante de Carne',
      'sv': 'Kryddig Nötköttsoppa',
      'th': 'ยุคแกแจ',
      'tr': 'Baharat Soslu Çorba',
      'vi': 'Cơm Bò Cay',
      'ru': 'Острый говяжий суп',
    },
    ingredients: [
      RecipeIngredient(name: '소고기', quantity: 300, unit: 'g'),
      RecipeIngredient(name: '고사리', quantity: 100, unit: 'g'),
      RecipeIngredient(name: '숙주', quantity: 200, unit: 'g'),
      RecipeIngredient(name: '대파', quantity: 3, unit: '대'),
      RecipeIngredient(name: '무', quantity: 0.2, unit: '개'),
    ],
  ),
  Recipe(
    id: 'r30',
    localizedNames: {
      'ko': '감자채볶음',
      'en': 'Stir-fried Julienned Potatoes',
      'ar': 'بطاطس مقلية رفيعة',
      'de': 'Gebratene Kartoffelstäbchen',
      'el': 'Τηγανιτές Πατάτες Ζουλιέν',
      'es': 'Patatas en juliana salteadas',
      'fr': 'Pommes de terre julienne sautées',
      'hi': 'तली कटी आलू',
      'it': 'Patate julienne saltate',
      'ja': '細切りジャガイモ炒め',
      'nl': 'Gebakken Aardappelstengels',
      'pl': 'Smażone ziemniaki julienne',
      'pt': 'Batata Palha Refogada',
      'sv': 'Stekt Potatisstrimmor',
      'th': 'มันฝรั่งเจอลิแอนทอด',
      'tr': 'Patates Çubukları Kızartılmış',
      'vi': 'Khoai Tây Cắt Sợi Chiên',
      'ru': 'Жареная соломка из картофеля',
    },
    ingredients: [
      RecipeIngredient(name: '감자', quantity: 2, unit: '개'),
      RecipeIngredient(name: '양파', quantity: 0.5, unit: '개'),
      RecipeIngredient(name: '당근', quantity: 0.2, unit: '개'),
    ],
  ),
  Recipe(
    id: 'r31',
    localizedNames: {
      'ko': '호박전',
      'en': 'Zucchini Pancake',
      'ar': 'فطيرة الكوسة',
      'de': 'Zucchini-Pfannkuchen',
      'el': 'Κολοκύθι Παγκέικ',
      'es': 'Tortita de calabacín',
      'fr': 'Pancake aux courgettes',
      'hi': 'तोरी पैनकेक',
      'it': 'Frittella di zucchine',
      'ja': 'ズッキーニチヂミ',
      'nl': 'Courgettepannenkoek',
      'pl': 'Naleśnik z cukinii',
      'pt': 'Panqueca de Abóbora',
      'sv': 'Zucchini Pannkaka',
      'th': 'แพนเค้กฟักทอง',
      'tr': 'Kabak Pancake',
      'vi': 'Bánh Roti Bí',
      'ru': 'Оладьи из цукини',
    },
    ingredients: [
      RecipeIngredient(name: '애호박', quantity: 1, unit: '개'),
      RecipeIngredient(name: '계란', quantity: 2, unit: '개'),
      RecipeIngredient(name: '밀가루', quantity: 0.5, unit: '컵'),
    ],
  ),
  Recipe(
    id: 'r32',
    localizedNames: {
      'ko': '김치전',
      'en': 'Kimchi Pancake',
      'ar': 'فطيرة الكيمتشي',
      'de': 'Kimchi-Pfannkuchen',
      'el': 'Κιμτσι Παγκέικ',
      'es': 'Tortita de kimchi',
      'fr': 'Pancake au kimchi',
      'hi': 'किमची पैनकेक',
      'it': 'Frittella di kimchi',
      'ja': 'キムチチヂミ',
      'nl': 'Kimchi Pannenkoek',
      'pl': 'Naleśnik z kimchi',
      'pt': 'Panqueca de Kimchi',
      'sv': 'Kimchi Pannkaka',
      'th': 'แพนเค้กกิมจิ',
      'tr': 'Kimchi Pancake',
      'vi': 'Bánh Kimchi',
      'ru': 'Оладьи с кимчи',
    },
    ingredients: [
      RecipeIngredient(name: '김치', quantity: 0.2, unit: '포기'),
      RecipeIngredient(name: '부침가루', quantity: 1, unit: '컵'),
      RecipeIngredient(name: '양파', quantity: 0.5, unit: '개'),
      RecipeIngredient(name: '오징어', quantity: 0.5, unit: '마리'),
    ],
  ),
  Recipe(
    id: 'r33',
    localizedNames: {
      'ko': '해물파전',
      'en': 'Seafood Green Onion Pancake',
      'ar': 'فطيرة المأكولات البحرية والبصل',
      'de': 'Meeresfrüchte-Zwiebel-Pfannkuchen',
      'el': 'Θαλασσινά Κρεμμύδι Παγκέικ',
      'es': 'Tortita de mariscos y cebolleta',
      'fr': 'Pancake aux fruits de mer et oignons verts',
      'hi': 'समुद्री खाद्य प्याज पैनकेक',
      'it': 'Frittella di frutti di mare e cipollotti',
      'ja': '海鮮ネギチヂミ',
      'nl': 'Zeevruchten Ui Pannenkoek',
      'pl': 'Naleśnik z owocami morza i szczypiorem',
      'pt': 'Panqueca de Frutos do Mar e Cebolinha',
      'sv': 'Skaldjur Lök Pannkaka',
      'th': 'แพนเค้กหอมเหลือบทะเล',
      'tr': 'Deniz Ürünleri Soğan Pancake',
      'vi': 'Bánh Hải Sản Hành Lá',
      'ru': 'Оладьи с морепродуктами и луком',
    },
    ingredients: [
      RecipeIngredient(name: '쪽파', quantity: 1, unit: '단'),
      RecipeIngredient(name: '오징어', quantity: 1, unit: '마리'),
      RecipeIngredient(name: '새우', quantity: 100, unit: 'g'),
      RecipeIngredient(name: '부침가루', quantity: 2, unit: '컵'),
      RecipeIngredient(name: '계란', quantity: 2, unit: '개'),
    ],
  ),
  Recipe(
    id: 'r34',
    localizedNames: {
      'ko': '계란말이',
      'en': 'Rolled Omelette',
      'ar': 'البيض المقلي الملفوف',
      'de': 'Gerolltes Omelett',
      'el': 'Περιστρεφόμενη Ωμελέτα',
      'es': 'Tortilla enrollada',
      'fr': 'Omelette roulée',
      'hi': 'रोल्ड आमलेट',
      'it': 'Omelette arrotolata',
      'ja': '卵焼き',
      'nl': 'Gerold Omelet',
      'pl': 'Zwinięty omlet',
      'pt': 'Omelete Enrolada',
      'sv': 'Rullad Omelett',
      'th': 'ไข่ม้วน',
      'tr': 'Sarılmış Omlet',
      'vi': 'Trứng Cuộn',
      'ru': 'Рулет из омлета',
    },
    ingredients: [
      RecipeIngredient(name: '계란', quantity: 5, unit: '개'),
      RecipeIngredient(name: '대파', quantity: 0.2, unit: '대'),
      RecipeIngredient(name: '당근', quantity: 0.1, unit: '개'),
    ],
  ),
];
