part of 'recipe_service.dart';

/// 기본 레시피 Part 3c: 해외 레시피 추가 (r53–r54)
final List<Recipe> _defaultRecipesPart3c = [
  Recipe(
    id: 'r53',
    localizedNames: {
      'en': 'Udon',
      'ar': 'اودون',
      'de': 'Udon',
      'el': 'Ουντον',
      'es': 'Udon',
      'fr': 'Udon',
      'hi': 'उदॉन',
      'it': 'Udon',
      'ja': 'うどん',
      'ko': '우동',
      'nl': 'Udon',
      'pl': 'Udon',
      'pt': 'Udon',
      'sv': 'Udon',
      'th': 'อูดง',
      'tr': 'Udon',
      'vi': 'Mì Udon',
      'ru': 'Удон',
    },
    cuisine: 'Japanese',
    ingredients: [
      RecipeIngredient(name: 'Udon Noodles', quantity: 1, unit: 'ea'),
      RecipeIngredient(name: 'Fish Cake', quantity: 1, unit: 'sheet'),
      RecipeIngredient(name: 'Green Onion', quantity: 0.5, unit: 'stalk'),
      RecipeIngredient(name: 'Crown Daisy', quantity: 20, unit: 'g'),
    ],
  ),
  Recipe(
    id: 'r54',
    localizedNames: {
      'en': 'Mapo Tofu',
      'ar': 'توفو ماپو',
      'de': 'Mapo Tofu',
      'el': 'Τόφου Μαπό',
      'es': 'Tofu Mapo',
      'fr': 'Tofu Mapo',
      'hi': 'माप टोफू',
      'it': 'Tofu Mapo',
      'ja': '麻婆豆腐',
      'ko': '마파두부',
      'nl': 'Mapo Tofu',
      'pl': 'Mapo Tofu',
      'pt': 'Tofu Mapo',
      'sv': 'Mapo Tofu',
      'th': 'เต้าหู้มาโปะ',
      'tr': 'Mapo Tofu',
      'vi': 'Tàu Hũ Ma Pô',
      'ru': 'Мапо тофу',
    },
    cuisine: 'Chinese',
    ingredients: [
      RecipeIngredient(name: 'Tofu', quantity: 1, unit: 'block'),
      RecipeIngredient(name: 'Pork', quantity: 100, unit: 'g'),
      RecipeIngredient(name: 'Green Onion', quantity: 0.5, unit: 'stalk'),
      RecipeIngredient(name: 'Doubanjiang', quantity: 2, unit: 'tbsp'),
    ],
  ),
];
