part of 'recipe_service.dart';

/// 기본 레시피 Part 3b: 해외 레시피 (r45–r54)
final List<Recipe> _defaultRecipesPart3b = [
  Recipe(
    id: 'r45',
    localizedNames: {
      'ko': '미역국',
      'en': 'Seaweed Soup',
      'ar': 'شوربة الأعشاب البحرية',
      'de': 'Algensuppe',
      'el': 'Σούπα Φυκών',
      'es': 'Sopa de algas',
      'fr': 'Soupe aux algues',
      'hi': 'समुद्री शैवाल सूप',
      'it': 'Zuppa di alghe',
      'ja': 'わかめスープ',
      'nl': 'Zeewiersop',
      'pl': 'Zupa z wodorostów',
      'pt': 'Sopa de Alga Marinha',
      'sv': 'Tångsoppa',
      'th': 'น้ำซุปหนองหญ้า',
      'tr': 'Yosun Çorbası',
      'vi': 'Súp Tảo Biển',
      'ru': 'Суп из водорослей',
    },
    ingredients: [
      RecipeIngredient(name: '미역', quantity: 20, unit: 'g'),
      RecipeIngredient(name: '소고기', quantity: 100, unit: 'g'),
      RecipeIngredient(name: '다진마늘', quantity: 1, unit: '큰술'),
      RecipeIngredient(name: '참기름', quantity: 1, unit: '큰술'),
    ],
  ),
  Recipe(
    id: 'r46',
    localizedNames: {
      'ko': '북역국',
      'en': 'Dried Pollack Soup',
      'ar': 'حساء منطقة الاستقرار المجففة',
      'de': 'Getrocknete Seelachs-Suppe',
      'el': 'Σούπα Ξηρής Ταράτσας',
      'es': 'Sopa de abadejo seco',
      'fr': 'Soupe de colin séché',
      'hi': 'सूखे पोलाक सूप',
      'it': 'Zuppa di merluzzo secco',
      'ja': '干しタラスープ',
      'nl': 'Gedroogde Seelaarssoep',
      'pl': 'Zupa z suszonego mintaja',
      'pt': 'Sopa de Bacalau Seco',
      'sv': 'Torkad Sejsoppa',
      'th': 'น้ำต้มปลาแห้ง',
      'tr': 'Kurutulmuş Balık Çorbası',
      'vi': 'Súp Cá Khô',
      'ru': 'Суп из сушёного минтая',
    },
    ingredients: [
      RecipeIngredient(name: '북어채', quantity: 50, unit: 'g'),
      RecipeIngredient(name: '무', quantity: 0.2, unit: '개'),
      RecipeIngredient(name: '계란', quantity: 1, unit: '개'),
      RecipeIngredient(name: '대파', quantity: 0.5, unit: '대'),
      RecipeIngredient(name: '참기름', quantity: 1, unit: '큰술'),
    ],
  ),
  Recipe(
    id: 'r47',
    localizedNames: {
      'ko': '떡국',
      'en': 'Rice Cake Soup',
      'ar': 'حساء كعكة الأرز',
      'de': 'Reiskuchen-Suppe',
      'el': 'Σούπα Κέικ Ρυζιού',
      'es': 'Sopa de pastel de arroz',
      'fr': 'Soupe de gâteau de riz',
      'hi': 'चावल की केक सूप',
      'it': 'Zuppa di torta di riso',
      'ja': '餅スープ',
      'nl': 'Rijstkoekensoep',
      'pl': 'Zupa z ciaśka ryżowego',
      'pt': 'Sopa de Bolo de Arroz',
      'sv': 'Riskakasopp',
      'th': 'น้ำข้าวเหนียว',
      'tr': 'Pirinç Kek Çorbası',
      'vi': 'Súp Bánh Gạo',
      'ru': 'Суп с рисовыми лепёшками',
    },
    ingredients: [
      RecipeIngredient(name: '떡국떡', quantity: 400, unit: 'g'),
      RecipeIngredient(name: '소고기', quantity: 100, unit: 'g'),
      RecipeIngredient(name: '계란', quantity: 1, unit: '개'),
      RecipeIngredient(name: '대파', quantity: 0.5, unit: '대'),
      RecipeIngredient(name: '김', quantity: 1, unit: '장'),
    ],
  ),
  Recipe(
    id: 'r48',
    localizedNames: {
      'ko': '수제비',
      'en': 'Hand-pulled Dough Soup',
      'ar': 'حساء العجين المسحوب يدويا',
      'de': 'Von Hand gezogene Nudelsuppe',
      'el': 'Σούπα Χεροποίητης Ζύμης',
      'es': 'Sopa de masa estirada a mano',
      'fr': 'Soupe de pâte étirée à la main',
      'hi': 'हाथ से खींचा हुआ आटा सूप',
      'it': 'Zuppa di pasta tirata a mano',
      'ja': '手ちぎり麵スープ',
      'nl': 'Handgetrokken Deegsoep',
      'pl': 'Zupa z ciasta ciągniętego ręcznie',
      'pt': 'Sopa de Massa Puxada à Mão',
      'sv': 'Handplockad Degsopp',
      'th': 'น้ำซุปแป้งถูเนื้อมือ',
      'tr': 'El ile Çektirilmiş Hamur Çorbası',
      'vi': 'Súp Bánh Kéo Tay',
      'ru': 'Суп с ручной лапшой',
    },
    ingredients: [
      RecipeIngredient(name: '밀가루', quantity: 2, unit: '컵'),
      RecipeIngredient(name: '감자', quantity: 1, unit: '개'),
      RecipeIngredient(name: '애호박', quantity: 0.3, unit: '개'),
      RecipeIngredient(name: '대파', quantity: 0.5, unit: '대'),
      RecipeIngredient(name: '바지락', quantity: 100, unit: 'g'),
    ],
  ),
  Recipe(
    id: 'r49',
    localizedNames: {
      'ko': '쭈면',
      'en': 'Spicy Chewy Noodles',
      'ar': 'نودلز حارة و مضغية',
      'de': 'Würzige zähe Nudeln',
      'el': 'Καυτό Κολλώδη Νουντλς',
      'es': 'Fideos picantes masticables',
      'fr': 'Nouilles épicées moelleuses',
      'hi': 'मसालेदार चबाने योग्य नूडल्स',
      'it': 'Tagliatelle piccanti gommose',
      'ja': '辛いもちもち麦',
      'nl': 'Pittige Kauwbare Noodles',
      'pl': 'Pikantne żujące makaron',
      'pt': 'Macarrão Mastigável Apimentado',
      'sv': 'Kryddig Tuggbar Nudlar',
      'th': 'ก๋วยเตี๋ยวเคี่ยว',
      'tr': 'Baharatlandırılmış Çiğnene Noodles',
      'vi': 'Mì Cay Nhai Cứng',
      'ru': 'Острая жевательная лапша',
    },
    ingredients: [
      RecipeIngredient(name: '쫄면', quantity: 200, unit: 'g'),
      RecipeIngredient(name: '콩나물', quantity: 100, unit: 'g'),
      RecipeIngredient(name: '양배추', quantity: 50, unit: 'g'),
      RecipeIngredient(name: '오이', quantity: 0.3, unit: '개'),
      RecipeIngredient(name: '계란', quantity: 0.5, unit: '개'),
    ],
  ),
  Recipe(
    id: 'r50',
    localizedNames: {
      'ko': '잌치국수',
      'en': 'Banquet Noodles',
      'ar': 'نودلز الولائم',
      'de': 'Festnudeln',
      'el': 'Δεξίωση Νουντλς',
      'es': 'Fideos de banquete',
      'fr': 'Nouilles de banquet',
      'hi': 'दावत नूडल्स',
      'it': 'Tagliatelle per banchetti',
      'ja': '宴会麦',
      'nl': 'Bankeetnudels',
      'pl': 'Makaron bankietowy',
      'pt': 'Macarrão para Banquete',
      'sv': 'Bankettnudlar',
      'th': 'ก๋วยเตี๋ยวเลี้ยง',
      'tr': 'Ziyafet Noodles',
      'vi': 'Mì Tiệc',
      'ru': 'Банкетная лапша',
    },
    ingredients: [
      RecipeIngredient(name: '소면', quantity: 200, unit: 'g'),
      RecipeIngredient(name: '애호박', quantity: 0.2, unit: '개'),
      RecipeIngredient(name: '당근', quantity: 0.1, unit: '개'),
      RecipeIngredient(name: '계란', quantity: 1, unit: '개'),
      RecipeIngredient(name: '김치', quantity: 50, unit: 'g'),
    ],
  ),
  // International Recipes (part kept here: r51–r52)
  Recipe(
    id: 'r51',
    localizedNames: {
      'en': 'Steak',
      'ar': 'لحم مشوي',
      'de': 'Fleisch',
      'el': 'Μπριζόλα',
      'es': 'Bistec',
      'fr': 'Bifteck',
      'hi': 'स्टेक',
      'it': 'Bistecca',
      'ja': 'ステーキ',
      'ko': '스테이크',
      'nl': 'Biefstuk',
      'pl': 'Stek',
      'pt': 'Bife',
      'sv': 'Biff',
      'th': 'สเต็ก',
      'tr': 'Biftek',
      'vi': 'Bít Tết',
      'ru': 'Стейк',
    },
    cuisine: 'Western',
    ingredients: [
      RecipeIngredient(name: 'Beef', quantity: 300, unit: 'g'),
      RecipeIngredient(name: 'Asparagus', quantity: 3, unit: 'ea'),
      RecipeIngredient(name: 'Garlic', quantity: 5, unit: 'clove'),
      RecipeIngredient(name: 'Butter', quantity: 20, unit: 'g'),
    ],
  ),
  Recipe(
    id: 'r52',
    localizedNames: {
      'en': 'Pasta',
      'ar': 'المعكرونة',
      'de': 'Nudeln',
      'el': 'Παστα',
      'es': 'Pasta',
      'fr': 'Pâtes',
      'hi': 'पास्ता',
      'it': 'Pasta',
      'ja': 'パスタ',
      'ko': '파스타',
      'nl': 'Pasta',
      'pl': 'Makaron',
      'pt': 'Massa',
      'sv': 'Pasta',
      'th': 'พาสต้า',
      'tr': 'Makarna',
      'vi': 'Mì Ý',
      'ru': 'Паста',
    },
    cuisine: 'Western',
    ingredients: [
      RecipeIngredient(name: 'Pasta', quantity: 100, unit: 'g'),
      RecipeIngredient(name: 'Garlic', quantity: 5, unit: 'clove'),
      RecipeIngredient(name: 'Olive Oil', quantity: 3, unit: 'tbsp'),
      RecipeIngredient(name: 'Peperoncino', quantity: 3, unit: 'ea'),
    ],
  ),
];
