part of 'recipe_service.dart';

/// 기본 레시피 Part 3: 한식 반찬·국·면 + 해외 + WHO 추천 (r35–r54, WHO)
final List<Recipe> _defaultRecipesPart3 = [
  Recipe(
    id: 'r35',
    name: '계란찜',
    ingredients: [
      RecipeIngredient(name: '계란', quantity: 3, unit: '개'),
      RecipeIngredient(name: '대파', quantity: 0.1, unit: '대'),
      RecipeIngredient(name: '새우젓', quantity: 0.5, unit: '큰술'),
    ],
  ),
  Recipe(
    id: 'r36',
    name: '두부조림',
    ingredients: [
      RecipeIngredient(name: '두부', quantity: 1, unit: '모'),
      RecipeIngredient(name: '양파', quantity: 0.5, unit: '개'),
      RecipeIngredient(name: '대파', quantity: 0.5, unit: '대'),
      RecipeIngredient(name: '고춧가루', quantity: 1, unit: '큰술'),
    ],
  ),
  Recipe(
    id: 'r37',
    name: '어묵볶음',
    ingredients: [
      RecipeIngredient(name: '어묵', quantity: 4, unit: '장'),
      RecipeIngredient(name: '양파', quantity: 0.5, unit: '개'),
      RecipeIngredient(name: '당근', quantity: 0.2, unit: '개'),
      RecipeIngredient(name: '대파', quantity: 0.5, unit: '대'),
    ],
  ),
  Recipe(
    id: 'r38',
    name: '진미채볶음',
    ingredients: [
      RecipeIngredient(name: '진미채', quantity: 200, unit: 'g'),
      RecipeIngredient(name: '고추장', quantity: 2, unit: '큰술'),
      RecipeIngredient(name: '마요네즈', quantity: 1, unit: '큰술'),
    ],
  ),
  Recipe(
    id: 'r39',
    name: '오이무침',
    ingredients: [
      RecipeIngredient(name: '오이', quantity: 2, unit: '개'),
      RecipeIngredient(name: '양파', quantity: 0.5, unit: '개'),
      RecipeIngredient(name: '고춧가루', quantity: 2, unit: '큰술'),
    ],
  ),
  Recipe(
    id: 'r40',
    name: '가지볶음',
    ingredients: [
      RecipeIngredient(name: '가지', quantity: 2, unit: '개'),
      RecipeIngredient(name: '양파', quantity: 0.5, unit: '개'),
      RecipeIngredient(name: '대파', quantity: 0.5, unit: '대'),
      RecipeIngredient(name: '굴소스', quantity: 1, unit: '큰술'),
    ],
  ),
  Recipe(
    id: 'r41',
    name: '닭볶음탕',
    ingredients: [
      RecipeIngredient(name: '닭고기', quantity: 1, unit: '마리'),
      RecipeIngredient(name: '감자', quantity: 2, unit: '개'),
      RecipeIngredient(name: '당근', quantity: 0.5, unit: '개'),
      RecipeIngredient(name: '양파', quantity: 1, unit: '개'),
      RecipeIngredient(name: '대파', quantity: 2, unit: '대'),
    ],
  ),
  Recipe(
    id: 'r42',
    name: '찜닭',
    ingredients: [
      RecipeIngredient(name: '닭고기', quantity: 1, unit: '마리'),
      RecipeIngredient(name: '당면', quantity: 100, unit: 'g'),
      RecipeIngredient(name: '감자', quantity: 2, unit: '개'),
      RecipeIngredient(name: '당근', quantity: 0.5, unit: '개'),
      RecipeIngredient(name: '양파', quantity: 1, unit: '개'),
      RecipeIngredient(name: '대파', quantity: 1, unit: '대'),
    ],
  ),
  Recipe(
    id: 'r43',
    name: '동태찌개',
    ingredients: [
      RecipeIngredient(name: '동태', quantity: 1, unit: '마리'),
      RecipeIngredient(name: '무', quantity: 0.3, unit: '개'),
      RecipeIngredient(name: '두부', quantity: 0.5, unit: '모'),
      RecipeIngredient(name: '대파', quantity: 1, unit: '대'),
      RecipeIngredient(name: '쑥갓', quantity: 50, unit: 'g'),
    ],
  ),
  Recipe(
    id: 'r44',
    name: '알탕',
    ingredients: [
      RecipeIngredient(name: '명란', quantity: 200, unit: 'g'),
      RecipeIngredient(name: '곤이', quantity: 100, unit: 'g'),
      RecipeIngredient(name: '무', quantity: 0.2, unit: '개'),
      RecipeIngredient(name: '콩나물', quantity: 100, unit: 'g'),
      RecipeIngredient(name: '대파', quantity: 1, unit: '대'),
    ],
  ),
  Recipe(
    id: 'r45',
    name: '미역국',
    ingredients: [
      RecipeIngredient(name: '미역', quantity: 20, unit: 'g'),
      RecipeIngredient(name: '소고기', quantity: 100, unit: 'g'),
      RecipeIngredient(name: '다진마늘', quantity: 1, unit: '큰술'),
      RecipeIngredient(name: '참기름', quantity: 1, unit: '큰술'),
    ],
  ),
  Recipe(
    id: 'r46',
    name: '북엇국',
    ingredients: [
      RecipeIngredient(name: '북어채', quantity: 50, unit: 'g'),
      RecipeIngredient(name: '무', quantity: 0.2, unit: '개'),
      RecipeIngredient(name: '계란', quantity: 1, unit: '개'),
      RecipeIngredient(name: '대파', quantity: 0.5, unit: '대'),
      RecipeIngredient(name: '참기름', quantity: 1, unit: '큰술'),
    ],
  ),
  Recipe(
    id: 'r47',
    name: '떡국',
    ingredients: [
      RecipeIngredient(name: '떡국떡', quantity: 400, unit: 'g'),
      RecipeIngredient(name: '소고기', quantity: 100, unit: 'g'),
      RecipeIngredient(name: '계란', quantity: 1, unit: '개'),
      RecipeIngredient(name: '대파', quantity: 0.5, unit: '대'),
      RecipeIngredient(name: '김', quantity: 1, unit: '장'),
    ],
  ),
  Recipe(
    id: 'r48',
    name: '수제비',
    ingredients: [
      RecipeIngredient(name: '밀가루', quantity: 2, unit: '컵'),
      RecipeIngredient(name: '감자', quantity: 1, unit: '개'),
      RecipeIngredient(name: '애호박', quantity: 0.3, unit: '개'),
      RecipeIngredient(name: '대파', quantity: 0.5, unit: '대'),
      RecipeIngredient(name: '바지락', quantity: 100, unit: 'g'),
    ],
  ),
  Recipe(
    id: 'r49',
    name: '쫄면',
    ingredients: [
      RecipeIngredient(name: '쫄면', quantity: 200, unit: 'g'),
      RecipeIngredient(name: '콩나물', quantity: 100, unit: 'g'),
      RecipeIngredient(name: '양배추', quantity: 50, unit: 'g'),
      RecipeIngredient(name: '오이', quantity: 0.3, unit: '개'),
      RecipeIngredient(name: '계란', quantity: 0.5, unit: '개'),
    ],
  ),
  Recipe(
    id: 'r50',
    name: '잔치국수',
    ingredients: [
      RecipeIngredient(name: '소면', quantity: 200, unit: 'g'),
      RecipeIngredient(name: '애호박', quantity: 0.2, unit: '개'),
      RecipeIngredient(name: '당근', quantity: 0.1, unit: '개'),
      RecipeIngredient(name: '계란', quantity: 1, unit: '개'),
      RecipeIngredient(name: '김치', quantity: 50, unit: 'g'),
    ],
  ),
  // International Recipes
  Recipe(
    id: 'r51',
    name: 'Steak (스테이크)',
    cuisine: 'Western',
    ingredients: [
      RecipeIngredient(name: 'Beef', quantity: 300, unit: 'g'),
      RecipeIngredient(name: 'Asparagus', quantity: 3, unit: 'ea'),
      RecipeIngredient(name: 'Garlic', quantity: 5, unit: 'clove'),
      RecipeIngredient(name: 'Butter', quantity: 20, unit: 'g'),
    ],
  ),
  Recipe(
    id: 'r52',
    name: 'Pasta (파스타)',
    cuisine: 'Western',
    ingredients: [
      RecipeIngredient(name: 'Pasta', quantity: 100, unit: 'g'),
      RecipeIngredient(name: 'Garlic', quantity: 5, unit: 'clove'),
      RecipeIngredient(name: 'Olive Oil', quantity: 3, unit: 'tbsp'),
      RecipeIngredient(name: 'Peperoncino', quantity: 3, unit: 'ea'),
    ],
  ),
  Recipe(
    id: 'r53',
    name: 'Udon (우동)',
    cuisine: 'Japanese',
    ingredients: [
      RecipeIngredient(name: 'Udon Noodles', quantity: 1, unit: 'ea'),
      RecipeIngredient(name: 'Fish Cake', quantity: 1, unit: 'sheet'),
      RecipeIngredient(name: 'Green Onion', quantity: 0.5, unit: 'stalk'),
      RecipeIngredient(name: 'Crown Daisy', quantity: 20, unit: 'g'),
    ],
  ),
  Recipe(
    id: 'r54',
    name: 'Mapo Tofu (마파두부)',
    cuisine: 'Chinese',
    ingredients: [
      RecipeIngredient(name: 'Tofu', quantity: 1, unit: 'block'),
      RecipeIngredient(name: 'Pork', quantity: 100, unit: 'g'),
      RecipeIngredient(name: 'Green Onion', quantity: 0.5, unit: 'stalk'),
      RecipeIngredient(name: 'Doubanjiang', quantity: 2, unit: 'tbsp'),
    ],
  ),
  // WHO 건강 추천 특별 메뉴
  Recipe(
    id: 'who_chicken',
    name: '🌟 닭고기·버섯·채소 된장탕 (WHO추천)',
    healthScore: 5,
    ingredients: [
      RecipeIngredient(name: '닭볶음탕용 닭고기', quantity: 900, unit: 'g'),
      RecipeIngredient(name: '느타리버섯', quantity: 500, unit: 'g'),
      RecipeIngredient(name: '표고버섯', quantity: 500, unit: 'g'),
      RecipeIngredient(name: '팽이버섯', quantity: 3, unit: '봉'),
      RecipeIngredient(name: '호박', quantity: 1, unit: '개'),
      RecipeIngredient(name: '양배추', quantity: 1.5, unit: 'kg'),
      RecipeIngredient(name: '당근', quantity: 1, unit: '개'),
      RecipeIngredient(name: '가지', quantity: 2, unit: '개'),
      RecipeIngredient(name: '양파', quantity: 1, unit: '망'),
      RecipeIngredient(name: '마늘', quantity: 1, unit: '망'),
      RecipeIngredient(name: '브로콜리', quantity: 1, unit: '개'),
      RecipeIngredient(name: '감자', quantity: 7, unit: '개'),
      RecipeIngredient(name: '피망', quantity: 2, unit: '개'),
      RecipeIngredient(name: '고추장', quantity: 1, unit: '숟가락'),
      RecipeIngredient(name: '된장', quantity: 1, unit: '숟가락'),
    ],
  ),
  Recipe(
    id: 'who_pork',
    name: '🌟 돼지고기·버섯·채소 된장탕 (WHO추천)',
    healthScore: 5,
    ingredients: [
      RecipeIngredient(name: '돼지고기 (앞다리/사태)', quantity: 900, unit: 'g'),
      RecipeIngredient(name: '느타리버섯', quantity: 500, unit: 'g'),
      RecipeIngredient(name: '표고버섯', quantity: 500, unit: 'g'),
      RecipeIngredient(name: '팽이버섯', quantity: 3, unit: '봉'),
      RecipeIngredient(name: '호박', quantity: 1, unit: '개'),
      RecipeIngredient(name: '양배추', quantity: 1.5, unit: 'kg'),
      RecipeIngredient(name: '당근', quantity: 1, unit: '개'),
      RecipeIngredient(name: '가지', quantity: 2, unit: '개'),
      RecipeIngredient(name: '양파', quantity: 1, unit: '망'),
      RecipeIngredient(name: '마늘', quantity: 1, unit: '망'),
      RecipeIngredient(name: '브로콜리', quantity: 1, unit: '개'),
      RecipeIngredient(name: '감자', quantity: 7, unit: '개'),
      RecipeIngredient(name: '피망', quantity: 2, unit: '개'),
      RecipeIngredient(name: '고추장', quantity: 1, unit: '숟가락'),
      RecipeIngredient(name: '된장', quantity: 1, unit: '숟가락'),
    ],
  ),
];
