part of 'recipe_service.dart';

/// 기본 레시피 Part 1b: 한식 찌개·볶음·구이 (r10–r17)
final List<Recipe> _defaultRecipesPart1b = [
  Recipe(
    id: 'r10',
    localizedNames: {
      'ko': '카레',
      'en': 'Curry',
      'ar': 'كاري',
      'de': 'Curry',
      'el': 'Κάρι',
      'es': 'Curry',
      'fr': 'Curry',
      'hi': 'करी',
      'it': 'Curry',
      'ja': 'カレー',
      'nl': 'Curry',
      'pl': 'Curry',
      'pt': 'Curry',
      'sv': 'Curry',
      'th': 'แกง',
      'tr': 'Korma',
      'vi': 'Cà Ri',
      'ru': 'Карри',
    },
    ingredients: [
      RecipeIngredient(name: '돼지고기', quantity: 200, unit: 'g'),
      RecipeIngredient(name: '감자', quantity: 2, unit: '개'),
      RecipeIngredient(name: '양파', quantity: 2, unit: '개'),
      RecipeIngredient(name: '당근', quantity: 0.5, unit: '개'),
    ],
  ),
  Recipe(
    id: 'r11',
    localizedNames: {
      'ko': '순두부찌개',
      'en': 'Soft Tofu Stew',
      'ar': 'يخنة التوفو الناعم',
      'de': 'Weiches Tofu-Eintopf',
      'el': 'Σούπα Μαλακής Σόγιας',
      'es': 'Estofado de tofu suave',
      'fr': 'Ragoût de tofu tendre',
      'hi': 'सॉफ्ट टोफू स्टू',
      'it': 'Stufato di tofu morbido',
      'ja': '絹ごし豆腐チゲ',
      'nl': 'Zachte Tofu-Stoofpot',
      'pl': 'Gulasz z miękkiego tofu',
      'pt': 'Estofado de Tofu Macio',
      'sv': 'Mjukt Tofu-Gryta',
      'th': 'แกงเต้าหู้นุ่ม',
      'tr': 'Yumuşak Tofu Güveç',
      'vi': 'Cơm Tàu Nước Mềm',
      'ru': 'Тушёное мягкое тофу',
    },
    ingredients: [
      RecipeIngredient(name: '순두부', quantity: 1, unit: '봉'),
      RecipeIngredient(name: '바지락', quantity: 200, unit: 'g'),
      RecipeIngredient(name: '계란', quantity: 1, unit: '개'),
      RecipeIngredient(name: '대파', quantity: 0.5, unit: '대'),
      RecipeIngredient(name: '양파', quantity: 0.5, unit: '개'),
    ],
  ),
  Recipe(
    id: 'r12',
    localizedNames: {
      'ko': '부대찌개',
      'en': 'Army Stew',
      'ar': 'يخنة الجيش',
      'de': 'Armee-Eintopf',
      'el': 'Στρατιωτική Σούπα',
      'es': 'Estofado del ejército',
      'fr': 'Ragoût de l\'armée',
      'hi': 'आर्मी स्टू',
      'it': 'Stufato dell\'esercito',
      'ja': '部隊チゲ',
      'nl': 'Leger-Stoofpot',
      'pl': 'Gulasz wojskowy',
      'pt': 'Estofado do Exército',
      'sv': 'Armé-Gryta',
      'th': 'แกงทหาร',
      'tr': 'Ordu Güveç',
      'vi': 'Cơm Quân Đội',
      'ru': 'Армейское тушёное',
    },
    ingredients: [
      RecipeIngredient(name: '햄', quantity: 200, unit: 'g'),
      RecipeIngredient(name: '소시지', quantity: 200, unit: 'g'),
      RecipeIngredient(name: '두부', quantity: 0.5, unit: '모'),
      RecipeIngredient(name: '라면사리', quantity: 1, unit: '개'),
      RecipeIngredient(name: '김치', quantity: 0.2, unit: '포기'),
      RecipeIngredient(name: '대파', quantity: 1, unit: '대'),
    ],
  ),
  Recipe(
    id: 'r13',
    localizedNames: {
      'ko': '소불고기',
      'en': 'Beef Bulgogi',
      'ar': 'لحم بقري بولغوغي',
      'de': 'Rind-Bulgogi',
      'el': 'Αγελάδα Βουλγόγι',
      'es': 'Bulgogi de ternera',
      'fr': 'Bulgogi de bœuf',
      'hi': 'बीफ बुल्गोगी',
      'it': 'Bulgogi di manzo',
      'ja': '牛プルコギ',
      'nl': 'Rundvlees Bulgogi',
      'pl': 'Bulgogi wołowe',
      'pt': 'Bulgogi de Carne',
      'sv': 'Nöt-Bulgogi',
      'th': 'เนื้อหมูเกาหลี',
      'tr': 'Sığır Bulgogi',
      'vi': 'Thịt Bò Nướng',
      'ru': 'Говяжье бульгоги',
    },
    ingredients: [
      RecipeIngredient(name: '소고기', quantity: 600, unit: 'g'),
      RecipeIngredient(name: '양파', quantity: 1, unit: '개'),
      RecipeIngredient(name: '대파', quantity: 1, unit: '대'),
      RecipeIngredient(name: '당근', quantity: 0.3, unit: '개'),
      RecipeIngredient(name: '버섯', quantity: 100, unit: 'g'),
    ],
  ),
  Recipe(
    id: 'r14',
    localizedNames: {
      'ko': '갈비찜',
      'en': 'Braised Short Ribs',
      'ar': 'أضلاع قصيرة محمرة',
      'de': 'Geschmorte Hochrippen',
      'el': 'Βραστά Κοντά Κόκαλα',
      'es': 'Costillas estofadas',
      'fr': 'Côtes braisées',
      'hi': 'ब्रेज्ड पसलियाँ',
      'it': 'Costine brasate',
      'ja': 'カルビチム',
      'nl': 'Geschoofde Korte Ribben',
      'pl': 'Duszone żeberka',
      'pt': 'Costelas Curtas Braiseadas',
      'sv': 'Brynt Korta Revben',
      'th': 'โครงกระดูกเนื้อยาง',
      'tr': 'Kasaplık Kısa Kaburga',
      'vi': 'Sườn Cort Nướng',
      'ru': 'Тушёные рёбрышки',
    },
    ingredients: [
      RecipeIngredient(name: '소갈비', quantity: 1, unit: 'kg'),
      RecipeIngredient(name: '무', quantity: 0.3, unit: '개'),
      RecipeIngredient(name: '당근', quantity: 1, unit: '개'),
      RecipeIngredient(name: '밤', quantity: 10, unit: '개'),
      RecipeIngredient(name: '대추', quantity: 10, unit: '개'),
    ],
  ),
  Recipe(
    id: 'r15',
    localizedNames: {
      'ko': '잡채',
      'en': 'Japchae',
      'ar': 'جابتشاي',
      'de': 'Japchae',
      'el': 'Ιαπβάε',
      'es': 'Japchae',
      'fr': 'Japchae',
      'hi': 'जापचे',
      'it': 'Japchae',
      'ja': 'チャプチェ',
      'nl': 'Japchae',
      'pl': 'Japchae',
      'pt': 'Japchae',
      'sv': 'Japchae',
      'th': 'จับแจ',
      'tr': 'Japchae',
      'vi': 'Chap Chae',
      'ru': 'Чапчхе',
    },
    ingredients: [
      RecipeIngredient(name: '당면', quantity: 250, unit: 'g'),
      RecipeIngredient(name: '시금치', quantity: 0.5, unit: '단'),
      RecipeIngredient(name: '당근', quantity: 0.5, unit: '개'),
      RecipeIngredient(name: '양파', quantity: 1, unit: '개'),
      RecipeIngredient(name: '돼지고기', quantity: 100, unit: 'g'),
      RecipeIngredient(name: '버섯', quantity: 100, unit: 'g'),
    ],
  ),
  Recipe(
    id: 'r16',
    localizedNames: {
      'ko': '떡볶이',
      'en': 'Tteokbokki',
      'ar': 'تيوك بوكي',
      'de': 'Tteokbokki',
      'el': 'Τεοκμποκι',
      'es': 'Tteokbokki',
      'fr': 'Tteokbokki',
      'hi': 'ट्टोकबोक्की',
      'it': 'Tteokbokki',
      'ja': 'トッポギ',
      'nl': 'Tteokbokki',
      'pl': 'Tteokbokki',
      'pt': 'Tteokbokki',
      'sv': 'Tteokbokki',
      'th': 'เทตกบกกี',
      'tr': 'Tteokbokki',
      'vi': 'Bánh Gạo Cay',
      'ru': 'Ттокбокки',
    },
    ingredients: [
      RecipeIngredient(name: '떡', quantity: 400, unit: 'g'),
      RecipeIngredient(name: '어묵', quantity: 3, unit: '장'),
      RecipeIngredient(name: '대파', quantity: 1, unit: '대'),
      RecipeIngredient(name: '양배추', quantity: 0.1, unit: '통'),
    ],
  ),
  Recipe(
    id: 'r17',
    localizedNames: {
      'ko': '비빔밥',
      'en': 'Bibimbap',
      'ar': 'بيبيمباب',
      'de': 'Bibimbap',
      'el': 'Βιβιμπάπ',
      'es': 'Bibimbap',
      'fr': 'Bibimbap',
      'hi': 'बिबिम्बाप',
      'it': 'Bibimbap',
      'ja': 'ビビンバ',
      'nl': 'Bibimbap',
      'pl': 'Bibimbap',
      'pt': 'Bibimbap',
      'sv': 'Bibimbap',
      'th': 'บิบิมบาบ',
      'tr': 'Bibimbap',
      'vi': 'Cơm Trộn',
      'ru': 'Бибимбап',
    },
    ingredients: [
      RecipeIngredient(name: '콩나물', quantity: 100, unit: 'g'),
      RecipeIngredient(name: '시금치', quantity: 0.3, unit: '단'),
      RecipeIngredient(name: '당근', quantity: 0.3, unit: '개'),
      RecipeIngredient(name: '계란', quantity: 1, unit: '개'),
      RecipeIngredient(name: '소고기', quantity: 50, unit: 'g'),
    ],
  ),
];
