part of 'recipe_service.dart';

/// 기본 레시피 Part 3a: 한식 반찬·국·면 (r35–r44)
final List<Recipe> _defaultRecipesPart3a = [
  Recipe(
    id: 'r35',
    localizedNames: {
      'ko': '계란짜',
      'en': 'Steamed Egg',
      'ar': 'بيضة مطبوخة بالبخار',
      'de': 'Gedämpftes Ei',
      'el': 'Ατμοποιημένο Αυγό',
      'es': 'Huevo al vapor',
      'fr': 'Œuf à la vapeur',
      'hi': 'उबली हुई अंडा',
      'it': 'Uovo al vapore',
      'ja': '茶碗蒸し',
      'nl': 'Gestoomde Ei',
      'pl': 'Gotowane jajko na parze',
      'pt': 'Ovo Cozido no Vapor',
      'sv': 'Ångkokd Ägg',
      'th': 'ไข่นึ่ง',
      'tr': 'Buğulanan Yumurta',
      'vi': 'Trứng Hấp',
      'ru': 'Паровое яйцо',
    },
    ingredients: [
      RecipeIngredient(name: '계란', quantity: 3, unit: '개'),
      RecipeIngredient(name: '대파', quantity: 0.1, unit: '대'),
      RecipeIngredient(name: '새우젓', quantity: 0.5, unit: '큰술'),
    ],
  ),
  Recipe(
    id: 'r36',
    localizedNames: {
      'ko': '두부조림',
      'en': 'Braised Tofu',
      'ar': 'توفو مطهو ببطء',
      'de': 'Geschmortes Tofu',
      'el': 'Τόφου Μαγειρεμένο',
      'es': 'Tofu estofado',
      'fr': 'Tofu braisé',
      'hi': 'ब्रेज्ड टोफू',
      'it': 'Tofu brasato',
      'ja': '豆腐の煮付け',
      'nl': 'Geschoofde Tofu',
      'pl': 'Duszone tofu',
      'pt': 'Tofu Braiseado',
      'sv': 'Braserad Tofu',
      'th': 'เต้าหู้นึ่ง',
      'tr': 'Braised Tofu',
      'vi': 'Tàu Hũ Kho',
      'ru': 'Тушёное тофу',
    },
    ingredients: [
      RecipeIngredient(name: '두부', quantity: 1, unit: '모'),
      RecipeIngredient(name: '양파', quantity: 0.5, unit: '개'),
      RecipeIngredient(name: '대파', quantity: 0.5, unit: '대'),
      RecipeIngredient(name: '고춧가루', quantity: 1, unit: '큰술'),
    ],
  ),
  Recipe(
    id: 'r37',
    localizedNames: {
      'ko': '어묵볶음',
      'en': 'Stir-fried Fish Cake',
      'ar': 'كعكة السمك المقلية بسرعة',
      'de': 'Gebratener Fischkuchen',
      'el': 'Τηγανιστή Τόρτα Ψαριού',
      'es': 'Pastel de pescado salteado',
      'fr': 'Gâteau de poisson sauté',
      'hi': 'तला हुआ मछली केक',
      'it': 'Torta di pesce saltata',
      'ja': '練り物炒め',
      'nl': 'Gebakken Viskake',
      'pl': 'Smażone ciastko rybne',
      'pt': 'Bolo de Peixe Refogado',
      'sv': 'Stekt Fiskbullar',
      'th': 'ปลาตัวอ่อนผ่องกึ่ง',
      'tr': 'Kızartılmış Balık Kek',
      'vi': 'Bánh Cá Chiên',
      'ru': 'Жареный рыбный кекс',
    },
    ingredients: [
      RecipeIngredient(name: '어묵', quantity: 4, unit: '장'),
      RecipeIngredient(name: '양파', quantity: 0.5, unit: '개'),
      RecipeIngredient(name: '당근', quantity: 0.2, unit: '개'),
      RecipeIngredient(name: '대파', quantity: 0.5, unit: '대'),
    ],
  ),
  Recipe(
    id: 'r38',
    localizedNames: {
      'ko': '진미채볶음',
      'en': 'Stir-fried Dried Squid',
      'ar': 'حبار مجفف مقلي بسرعة',
      'de': 'Gebratener getrockneter Tintenfisch',
      'el': 'Ξηραμένo Καλάμαρι Τηγανιστό',
      'es': 'Calamares secos salteados',
      'fr': 'Calmars séchés sautés',
      'hi': 'तली हुई सूखी स्क्विड',
      'it': 'Calamari secchi saltati',
      'ja': 'イカの切り身炒め',
      'nl': 'Gebakken Gedroogde Inktvis',
      'pl': 'Smażone suszone kałamarnice',
      'pt': 'Lula Seca Refogada',
      'sv': 'Stekt Torrkad Bläckfisk',
      'th': 'ปลาหมึกแห้งทอด',
      'tr': 'Kurutulmuş Mürekkep Balığı Kızartılmış',
      'vi': 'Mực Khô Chiên',
      'ru': 'Жареные сушёные кальмары',
    },
    ingredients: [
      RecipeIngredient(name: '진미채', quantity: 200, unit: 'g'),
      RecipeIngredient(name: '고추장', quantity: 2, unit: '큰술'),
      RecipeIngredient(name: '마요네즈', quantity: 1, unit: '큰술'),
    ],
  ),
  Recipe(
    id: 'r39',
    localizedNames: {
      'ko': '오이무침',
      'en': 'Cucumber Salad',
      'ar': 'سلطة الخيار',
      'de': 'Gurkensalat',
      'el': 'Σαλάτα Αγγουριού',
      'es': 'Ensalada de pepino',
      'fr': 'Salade de concombre',
      'hi': 'ककड़ी सलाद',
      'it': 'Insalata di cetrioli',
      'ja': '胡瓜の和え物',
      'nl': 'Komkommer Salade',
      'pl': 'Sałatka z ogórka',
      'pt': 'Salada de Pepino',
      'sv': 'Gurksallad',
      'th': 'สลัดแตงกวา',
      'tr': 'Salatalık Salatası',
      'vi': 'Salad Dưa Chuột',
      'ru': 'Салат из огурцов',
    },
    ingredients: [
      RecipeIngredient(name: '오이', quantity: 2, unit: '개'),
      RecipeIngredient(name: '양파', quantity: 0.5, unit: '개'),
      RecipeIngredient(name: '고춧가루', quantity: 2, unit: '큰술'),
    ],
  ),
  Recipe(
    id: 'r40',
    localizedNames: {
      'ko': '가지볶음',
      'en': 'Stir-fried Eggplant',
      'ar': 'باذنجان مقلي بسرعة',
      'de': 'Gebratene Aubergine',
      'el': 'Τηγανιστό Μελιτζάνι',
      'es': 'Berenjenas salteadas',
      'fr': 'Aubergines sautées',
      'hi': 'तला हुआ बैंगन',
      'it': 'Melanzane saltate',
      'ja': '茄子炒め',
      'nl': 'Gebakken Aubergine',
      'pl': 'Smażone bakłażany',
      'pt': 'Berinjela Refogada',
      'sv': 'Stekt Aubergine',
      'th': 'มะเขือทอด',
      'tr': 'Kızartılmış Patlıcan',
      'vi': 'Cà Chua Chiên',
      'ru': 'Жареные баклажаны',
    },
    ingredients: [
      RecipeIngredient(name: '가지', quantity: 2, unit: '개'),
      RecipeIngredient(name: '양파', quantity: 0.5, unit: '개'),
      RecipeIngredient(name: '대파', quantity: 0.5, unit: '대'),
      RecipeIngredient(name: '굴소스', quantity: 1, unit: '큰술'),
    ],
  ),
  Recipe(
    id: 'r41',
    localizedNames: {
      'ko': '닭볶음탕',
      'en': 'Braised Spicy Chicken',
      'ar': 'دجاج مطهو بحرارة حادة',
      'de': 'Geschmortes scharfes Huhn',
      'el': 'Κοτόπουλο Κατσαρόλα Καυτό',
      'es': 'Pollo estofado picante',
      'fr': 'Poulet braisé épicé',
      'hi': 'मसालेदार चिकन',
      'it': 'Pollo brasato piccante',
      'ja': '鶏肉の辛煮',
      'nl': 'Geschoofde Pikante Kip',
      'pl': 'Duszony pikantny kurczak',
      'pt': 'Frango Braiseado Apimentado',
      'sv': 'Braserad Kryddig Kyckling',
      'th': 'ไก่แบบจำลอง',
      'tr': 'Tavuk Güveç Baharat',
      'vi': 'Gà Nướng Cay Nho Nhỏ',
      'ru': 'Тушёная острая курица',
    },
    ingredients: [
      RecipeIngredient(name: '닭고기', quantity: 1, unit: '마리'),
      RecipeIngredient(name: '감자', quantity: 2, unit: '개'),
      RecipeIngredient(name: '당근', quantity: 0.5, unit: '개'),
      RecipeIngredient(name: '양파', quantity: 1, unit: '개'),
      RecipeIngredient(name: '대파', quantity: 2, unit: '대'),
    ],
  ),
  Recipe(
    id: 'r42',
    localizedNames: {
      'ko': '짜닭',
      'en': 'Braised Chicken',
      'ar': 'دجاج مطهو ببطء',
      'de': 'Geschmortes Huhn',
      'el': 'Κοτόπουλο Μαγειρεμένο',
      'es': 'Pollo estofado',
      'fr': 'Poulet braisé',
      'hi': 'ब्रेज्ड चिकन',
      'it': 'Pollo brasato',
      'ja': '鶏肉の煮物',
      'nl': 'Geschoofde Kip',
      'pl': 'Duszony kurczak',
      'pt': ' Frango Braiseado',
      'sv': 'Braserad Kyckling',
      'th': 'ไก่นึ่ง',
      'tr': 'Tavuk Güveç',
      'vi': 'Gà Kho',
      'ru': 'Тушёная курица',
    },
    ingredients: [
      RecipeIngredient(name: '닭고기', quantity: 1, unit: '마리'),
      RecipeIngredient(name: '당면', quantity: 100, unit: 'g'),
      RecipeIngredient(name: '감자', quantity: 2, unit: '개'),
      RecipeIngredient(name: '당근', quantity: 0.5, unit: '개'),
      RecipeIngredient(name: '양파', quantity: 1, unit: '개'),
      RecipeIngredient(name: '대파', quantity: 1, unit: '대'),
    ],
  ),
  Recipe(
    id: 'r43',
    localizedNames: {
      'ko': '동태찌개',
      'en': 'Pollack Stew',
      'ar': 'حساء منطقة الاستقرار',
      'de': 'Seelachs-Eintopf',
      'el': 'Σούπα Σκορπίων',
      'es': 'Estofado de abadejo',
      'fr': 'Ragoût de colin',
      'hi': 'पोलाक स्टू',
      'it': 'Stufato di merluzzo',
      'ja': '凍結タラのチゲ',
      'nl': 'Pollack-Stoofpot',
      'pl': 'Gulasz z mintaja',
      'pt': 'Estofado de Bacalau',
      'sv': 'Sej-Gryta',
      'th': 'แกงปลาคอด',
      'tr': 'Balık Güveç',
      'vi': 'Cơm Cá Tuyết',
      'ru': 'Тушёная минтай',
    },
    ingredients: [
      RecipeIngredient(name: '동태', quantity: 1, unit: '마리'),
      RecipeIngredient(name: '무', quantity: 0.3, unit: '개'),
      RecipeIngredient(name: '두부', quantity: 0.5, unit: '모'),
      RecipeIngredient(name: '대파', quantity: 1, unit: '대'),
      RecipeIngredient(name: '쑥갓', quantity: 50, unit: 'g'),
    ],
  ),
  Recipe(
    id: 'r44',
    localizedNames: {
      'ko': '알탕',
      'en': 'Fish Roe Stew',
      'ar': 'حساء بيض السمك',
      'de': 'Fischrogen-Eintopf',
      'el': 'Αυγοταραχή Σούπα',
      'es': 'Estofado de huevas de pescado',
      'fr': 'Ragoût d\'œufs de poisson',
      'hi': 'मछली रो स्टू',
      'it': 'Stufato di uova di pesce',
      'ja': '魚卵チゲ',
      'nl': 'Visrogge-Stoofpot',
      'pl': 'Gulasz z ikry rybnej',
      'pt': 'Estofado de Ova de Peixe',
      'sv': 'Fiskrom-Gryta',
      'th': 'แกงไข่ปลา',
      'tr': 'Balık Yumurtası Güveç',
      'vi': 'Cơm Trứng Cá',
      'ru': 'Тушёная рыбная икра',
    },
    ingredients: [
      RecipeIngredient(name: '명란', quantity: 200, unit: 'g'),
      RecipeIngredient(name: '곤이', quantity: 100, unit: 'g'),
      RecipeIngredient(name: '무', quantity: 0.2, unit: '개'),
      RecipeIngredient(name: '콩나물', quantity: 100, unit: 'g'),
      RecipeIngredient(name: '대파', quantity: 1, unit: '대'),
    ],
  ),
];
