part of 'shopping_category_rules.dart';

/// 식자재 구매 (과일/유제품/계란/주식류)
const Map<String, ShoppingCategoryPair> _groceryKeywords = {
  '사과': ShoppingCategoryRules.foodGrocery,
  '배': ShoppingCategoryRules.foodGrocery,
  '바나나': ShoppingCategoryRules.foodGrocery,
  '포도': ShoppingCategoryRules.foodGrocery,
  '딸기': ShoppingCategoryRules.foodGrocery,
  '수박': ShoppingCategoryRules.foodGrocery,
  '참외': ShoppingCategoryRules.foodGrocery,
  '귤': ShoppingCategoryRules.foodGrocery,
  '오렌지': ShoppingCategoryRules.foodGrocery,
  '토마토': ShoppingCategoryRules.foodGrocery,
  '방울토마토': ShoppingCategoryRules.foodGrocery,
  '키위': ShoppingCategoryRules.foodGrocery,
  '블루베리': ShoppingCategoryRules.foodGrocery,
  '망고': ShoppingCategoryRules.foodGrocery,
  '파인애플': ShoppingCategoryRules.foodGrocery,
  '복숭아': ShoppingCategoryRules.foodGrocery,
  '자두': ShoppingCategoryRules.foodGrocery,
  '체리': ShoppingCategoryRules.foodGrocery,
  '감': ShoppingCategoryRules.foodGrocery,
  '배추': ShoppingCategoryRules.foodGrocery,
  '무': ShoppingCategoryRules.foodGrocery,
  '양파': ShoppingCategoryRules.foodGrocery,
  '파': ShoppingCategoryRules.foodGrocery,
  '마늘': ShoppingCategoryRules.foodGrocery,
  '고추': ShoppingCategoryRules.foodGrocery,
  '오이': ShoppingCategoryRules.foodGrocery,
  '당근': ShoppingCategoryRules.foodGrocery,
  '감자': ShoppingCategoryRules.foodGrocery,
  '고구마': ShoppingCategoryRules.foodGrocery,
  '상추': ShoppingCategoryRules.foodGrocery,
  '깻잎': ShoppingCategoryRules.foodGrocery,
  '시금치': ShoppingCategoryRules.foodGrocery,
  '콩나물': ShoppingCategoryRules.foodGrocery,
  '숙주': ShoppingCategoryRules.foodGrocery,
  '버섯': ShoppingCategoryRules.foodGrocery,
  '팽이': ShoppingCategoryRules.foodGrocery,
  '새송이': ShoppingCategoryRules.foodGrocery,
  '표고': ShoppingCategoryRules.foodGrocery,
  '브로콜리': ShoppingCategoryRules.foodGrocery,
  '양배추': ShoppingCategoryRules.foodGrocery,
  '파프리카': ShoppingCategoryRules.foodGrocery,
  '피망': ShoppingCategoryRules.foodGrocery,
  '애호박': ShoppingCategoryRules.foodGrocery,
  '호박': ShoppingCategoryRules.foodGrocery,
  '가지': ShoppingCategoryRules.foodGrocery,
  '우유': ShoppingCategoryRules.foodGrocery,
  '치즈': ShoppingCategoryRules.foodGrocery,
  '요거': ShoppingCategoryRules.foodGrocery,
  '요구르트': ShoppingCategoryRules.foodGrocery,
  '버터': ShoppingCategoryRules.foodGrocery,
  '생크림': ShoppingCategoryRules.foodGrocery,
  '계란': ShoppingCategoryRules.foodGrocery,
  '달걀': ShoppingCategoryRules.foodGrocery,
  '빵': ShoppingCategoryRules.foodGrocery,
  '식빵': ShoppingCategoryRules.foodGrocery,
  '베이글': ShoppingCategoryRules.foodGrocery,
  '라면': ShoppingCategoryRules.foodGrocery,
  '컵라면': ShoppingCategoryRules.foodGrocery,
  '쌀': ShoppingCategoryRules.foodGrocery,
  '잡곡': ShoppingCategoryRules.foodGrocery,
  '현미': ShoppingCategoryRules.foodGrocery,
  '콩': ShoppingCategoryRules.foodGrocery,
  '두부': ShoppingCategoryRules.foodGrocery,
  '김치': ShoppingCategoryRules.foodGrocery,
  '단무지': ShoppingCategoryRules.foodGrocery,
  '김': ShoppingCategoryRules.foodGrocery,
  '미역': ShoppingCategoryRules.foodGrocery,
  '다시마': ShoppingCategoryRules.foodGrocery,
  '멸치': ShoppingCategoryRules.foodGrocery,
  '식용유': ShoppingCategoryRules.foodGrocery,
  '참기름': ShoppingCategoryRules.foodGrocery,
  '들기름': ShoppingCategoryRules.foodGrocery,
  '간장': ShoppingCategoryRules.foodGrocery,
  '고추장': ShoppingCategoryRules.foodGrocery,
  '된장': ShoppingCategoryRules.foodGrocery,
  '쌈장': ShoppingCategoryRules.foodGrocery,
  '설탕': ShoppingCategoryRules.foodGrocery,
  '소금': ShoppingCategoryRules.foodGrocery,
  '식초': ShoppingCategoryRules.foodGrocery,
  '밀가루': ShoppingCategoryRules.foodGrocery,
  '부침가루': ShoppingCategoryRules.foodGrocery,
  '튀김가루': ShoppingCategoryRules.foodGrocery,
  '카레': ShoppingCategoryRules.foodGrocery,
  '짜장': ShoppingCategoryRules.foodGrocery,
};

/// 간식
const Map<String, ShoppingCategoryPair> _snackKeywords = {
  '과자': ShoppingCategoryRules.foodSnack,
  '스낵': ShoppingCategoryRules.foodSnack,
  '쿠키': ShoppingCategoryRules.foodSnack,
  '비스킷': ShoppingCategoryRules.foodSnack,
  '초콜릿': ShoppingCategoryRules.foodSnack,
  '캔디': ShoppingCategoryRules.foodSnack,
  '사탕': ShoppingCategoryRules.foodSnack,
  '젤리': ShoppingCategoryRules.foodSnack,
  '껌': ShoppingCategoryRules.foodSnack,
  '아이스': ShoppingCategoryRules.foodSnack,
  '하드': ShoppingCategoryRules.foodSnack,
  '콘': ShoppingCategoryRules.foodSnack,
  '떡': ShoppingCategoryRules.foodSnack,
  '한과': ShoppingCategoryRules.foodSnack,
  '견과': ShoppingCategoryRules.foodSnack,
  '아몬드': ShoppingCategoryRules.foodSnack,
  '땅콩': ShoppingCategoryRules.foodSnack,
  '간식': ShoppingCategoryRules.foodSnack,
};

/// 가공식품
const Map<String, ShoppingCategoryPair> _processedKeywords = {
  '햄': ShoppingCategoryRules.foodProcessed,
  '소시지': ShoppingCategoryRules.foodProcessed,
  '베이컨': ShoppingCategoryRules.foodProcessed,
  '어묵': ShoppingCategoryRules.foodProcessed,
  '맛살': ShoppingCategoryRules.foodProcessed,
  '만두': ShoppingCategoryRules.foodProcessed,
  '물만두': ShoppingCategoryRules.foodProcessed,
  '군만두': ShoppingCategoryRules.foodProcessed,
  '돈가스': ShoppingCategoryRules.foodProcessed,
  '너겟': ShoppingCategoryRules.foodProcessed,
  '피자': ShoppingCategoryRules.foodProcessed,
  '치킨': ShoppingCategoryRules.foodProcessed,
  '냉동': ShoppingCategoryRules.foodProcessed,
  '즉석': ShoppingCategoryRules.foodProcessed,
  '레토르트': ShoppingCategoryRules.foodProcessed,
  '참치캔': ShoppingCategoryRules.foodProcessed,
  '참치': ShoppingCategoryRules.foodProcessed,
  '스팸': ShoppingCategoryRules.foodProcessed,
  '통조림': ShoppingCategoryRules.foodProcessed,
  '골뱅이': ShoppingCategoryRules.foodProcessed,
  '훈제': ShoppingCategoryRules.foodProcessed,
};

/// 육류
const Map<String, ShoppingCategoryPair> _meatKeywords = {
  // 돼지
  '돼지고기': ShoppingCategoryRules.foodMeat,
  '돼지': ShoppingCategoryRules.foodMeat,
  '삼겹': ShoppingCategoryRules.foodMeat,
  '목살': ShoppingCategoryRules.foodMeat,
  '앞다리': ShoppingCategoryRules.foodMeat,
  '뒷다리': ShoppingCategoryRules.foodMeat,
  '항정': ShoppingCategoryRules.foodMeat,
  '갈비': ShoppingCategoryRules.foodMeat,
  '등심': ShoppingCategoryRules.foodMeat,
  '안심': ShoppingCategoryRules.foodMeat,
  // 소
  '소고기': ShoppingCategoryRules.foodMeat,
  '한우': ShoppingCategoryRules.foodMeat,
  '불고기': ShoppingCategoryRules.foodMeat,
  '국거리': ShoppingCategoryRules.foodMeat,
  '구이': ShoppingCategoryRules.foodMeat,
  '스테이크': ShoppingCategoryRules.foodMeat,
  '차돌': ShoppingCategoryRules.foodMeat,
  '양지': ShoppingCategoryRules.foodMeat,
  // 닭/오리
  '닭고기': ShoppingCategoryRules.foodMeat,
  '닭': ShoppingCategoryRules.foodMeat,
  '생닭': ShoppingCategoryRules.foodMeat,
  '닭가슴살': ShoppingCategoryRules.foodMeat,
  '닭다리': ShoppingCategoryRules.foodMeat,
  '닭날개': ShoppingCategoryRules.foodMeat,
  '오리': ShoppingCategoryRules.foodMeat,
  '훈제오리': ShoppingCategoryRules.foodMeat,
  // Generic
  '고기': ShoppingCategoryRules.foodMeat,
  '육류': ShoppingCategoryRules.foodMeat,
  '정육': ShoppingCategoryRules.foodMeat,
};

/// 음료
const Map<String, ShoppingCategoryPair> _drinkKeywords = {
  '커피': ShoppingCategoryRules.foodDrink,
  '원두': ShoppingCategoryRules.foodDrink,
  '믹스커피': ShoppingCategoryRules.foodDrink,
  '음료': ShoppingCategoryRules.foodDrink,
  '탄산': ShoppingCategoryRules.foodDrink,
  '콜라': ShoppingCategoryRules.foodDrink,
  '사이다': ShoppingCategoryRules.foodDrink,
  '주스': ShoppingCategoryRules.foodDrink,
  '생수': ShoppingCategoryRules.foodDrink,
  '물': ShoppingCategoryRules.foodDrink,
  '차': ShoppingCategoryRules.foodDrink,
  '녹차': ShoppingCategoryRules.foodDrink,
  '홍차': ShoppingCategoryRules.foodDrink,
  '두유': ShoppingCategoryRules.foodDrink,
  '에너지드링크': ShoppingCategoryRules.foodDrink,
  '이온음료': ShoppingCategoryRules.foodDrink,
};

/// 주류
const Map<String, ShoppingCategoryPair> _alcoholKeywords = {
  '막걸리': ShoppingCategoryRules.alcohol,
  '소주': ShoppingCategoryRules.alcohol,
  '맥주': ShoppingCategoryRules.alcohol,
  '와인': ShoppingCategoryRules.alcohol,
  '위스키': ShoppingCategoryRules.alcohol,
  '보드카': ShoppingCategoryRules.alcohol,
  '고량주': ShoppingCategoryRules.alcohol,
  '사케': ShoppingCategoryRules.alcohol,
  // Broad matches (fallback)
  '주류': ShoppingCategoryRules.alcohol,
  '술': ShoppingCategoryRules.alcohol,
};
